### ISSUE TITLE
bax2bam needs to be on github

### ISSUE THREAD

**Issue by nlhepler** [PacificBiosciences/pbccs#62]
The point of #61 is absent without a way to marshall data into ccs-compatible form.

**Comment by dalexander** [comment]
@bnbowman , since I think you had expressed interest in becoming the point-man for bax2bam, I think ti would make sense for you to look into this.  Because of internal dependencies, this is going to have to be done using git-p4, we can't move the canonical repo to git.  Let me email you my slide deck on how to use git-p4 in our environment.

**Comment by Owen-haha** [comment]
@dalexander I am also very interested in testing the bax2bam. Can you also email me the software? Thanks!

**Comment by nlhepler** [comment]
it is! now included with blasr
